In [ ]:
s = "Hi there Nikil!"

In [ ]:
print(s.split())

['Hi', 'there', 'Nikil!']


In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print("The diameter of {planet} is {diameter} kilometers".format(planet="Earth",diameter=12742))

The diameter of Earth is 12742 kilometers


In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print( d['k1'][3]['tricky'][3]['target'][3])

hello


In [ ]:
import numpy as np

In [ ]:
Arr=np.array([0,0,0,0,0,0,0,0,0,0])
Arr1=np.array([5,5,5,5,5,5,5,5,5,5])

In [ ]:
print(Arr)
print(Arr1)

[0 0 0 0 0 0 0 0 0 0]
[5 5 5 5 5 5 5 5 5 5]


In [ ]:
Arr2=np.arange(20,35,2)
print(Arr2)

[20 22 24 26 28 30 32 34]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
arr = np.concatenate((a,b))
print(arr)

[1 2 3 4 5 6]


In [ ]:
import pandas as pd

In [ ]:
df={
    "Name":['a','b','c'],
    "Marks":[10,20,30]
}

In [ ]:
dataframe = pd.DataFrame(df)
print(dataframe)

  Name  Marks
0    a     10
1    b     20
2    c     30


In [ ]:
d=pd.date_range(start='1/1/2023', end='10/02/2023')

In [ ]:
print(d)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')


In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
df = pd.DataFrame(lists, columns =['F_No', 'Name', 'L_No'],
                                           dtype = int) 
print(df)

   F_No Name  L_No
0     1  aaa    22
1     2  bbb    25
2     3  ccc    24


/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: Could not cast to int64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised
  exec(code_obj, self.user_global_ns, self.user_ns)
